version: '3'

services:
  db:
    image: postgres
    volumes:
      - ./data/db:/var/lib/postgresql/data
    ports:
      - 5432:5432
    env_file:
      - .env
  api:
    build: .
    volumes:
      - ./:/usr/app/
    ports:
    - 3000:3000
    env_file:
      - .env