version: '3'

services:
  db:
    image: postgres
    volumes:
      - ./data/db:/var/lib/postgresql/data
    ports:
      - 5432:5432
    env_file:
      - .env

  api:
    build: .
    volumes:
      - ./src:/usr/app/src
    ports:
    - 3000:3000
    - 9229:9229
    env_file:
      - .env