version: '3'

services:
  db:
    image: postgres
    volumes:
      - ./data/db:/var/lib/postgresql/data
    env_file:
      - .env

  api:
    build: .
    volumes:
      - ./src:/usr/app/src
    ports:
      - 3000:3000
    env_file:
      - .env
    environment:
      - DB_HOST=db
